# -*- coding: utf-8 -*-
"""abmil_common

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Ctah0bViHGZrmPy6Z0d0K_d5OWWGWnt

# ABMIL Shared Pipeline Components
This section initialises the script parameters and imports required libraries
for mathematical operations, deep learning models (PyTorch, timm) and
evaluation metrics (scikit-learn).
"""

# Used by NB03, NB04, NB05 (and any future backbone notebooks).

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import gc
from torch.utils.data import Dataset
from sklearn.metrics import f1_score, roc_auc_score, confusion_matrix, matthews_corrcoef
from sklearn.calibration import calibration_curve
from torch.utils.data import DataLoader
import timm

"""### Data Normalisation & Model Backbone Builder

Converts standard ImageNet mean/std values into PyTorch CUDA tensors for fast GPU-based image normalisation
"""

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

def get_normalisation_tensors(device):
    mean = torch.tensor(IMAGENET_MEAN, dtype=torch.float32, device=device).view(1, 3, 1, 1)
    std  = torch.tensor(IMAGENET_STD,  dtype=torch.float32, device=device).view(1, 3, 1, 1)
    return mean, std

"""Uses `timm` to load a pre-trained feature extractor backbone
  without its default final classification head.
"""

def build_backbone(model_name, pretrained=True):
    return timm.create_model(model_name, pretrained=pretrained, num_classes=0)

"""### Patch Dataset and Classifier Modules

Custom PyTorch dataset wrapping NumPy patch images and labels.
"""

class PatchDataset(Dataset):
    def __init__(self, X_np, y_np):
        self.X = X_np
        self.y = torch.from_numpy(y_np).float()

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        patch = torch.from_numpy(self.X[idx]).float()
        return patch.permute(2, 0, 1), self.y[idx]

"""Integrates a backbone feature extractor with a single linear
  layer to classify individual image patches
"""

class PatchClassifier(nn.Module):
    def __init__(self, backbone, feat_dim):
        super().__init__()
        self.backbone = backbone
        self.head = nn.Linear(feat_dim, 1)

    def forward(self, x):
        return self.head(self.backbone(x)).squeeze(1)

"""### Stage 1 Training Pipeline
Runs the training and validation loop for a single fold of the patch classifier:
- Handles mixed-precision training (torch.amp.autocast) for speed and memory efficiency.
- Calculates BCE loss adjusted by class weights for imbalance.
- Applies early stopping based on validation loss and saves the best model checkpoint.
"""

def train_stage1_fold(model_name, X_all, y_all, train_idx, val_idx, class_weight_dict,
                       optimiser_name, lr, weight_decay, save_path,
                       device, patch_size=224, batch_size=128,
                       epochs=15, patience=5):
    # Trains ONE Stage 1 patch classifier and saves the best checkpoint.
    # Same procedure for every backbone and every fold so only model_name
    # and the parameters (optimiser/lr/weight_decay) differ between calls.

    backbone = build_backbone(model_name, pretrained=True).to(device)
    with torch.no_grad():
        _dummy = torch.zeros(2, 3, patch_size, patch_size, device=device)
        feat_dim = backbone(_dummy).shape[1]
    del _dummy

    patch_model = PatchClassifier(backbone, feat_dim).to(device)

    pos_weight_val = class_weight_dict[1] / class_weight_dict[0]
    criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight_val, device=device))

    if optimiser_name == "AdamW":
        optimiser = optim.AdamW(patch_model.parameters(), lr=lr, weight_decay=weight_decay)
    else:
        optimiser = optim.Adam(patch_model.parameters(), lr=lr, weight_decay=weight_decay)

    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimiser, mode='min', factor=0.5, patience=3)
    mean_gpu, std_gpu = get_normalisation_tensors(device)

    train_dl = DataLoader(IndexedPatchDataset(X_all, y_all, train_idx), batch_size=batch_size,
                           shuffle=True, num_workers=2, pin_memory=True)
    val_dl   = DataLoader(IndexedPatchDataset(X_all, y_all, val_idx), batch_size=batch_size,
                           shuffle=False, num_workers=2, pin_memory=True)

    scaler = torch.amp.GradScaler('cuda')
    best_val_loss, patience_ctr = float("inf"), 0
    history = {"train_loss": [], "val_loss": [], "val_auc": []}

    for epoch in range(1, epochs + 1):
        patch_model.train()
        running_loss = 0.0
        for patches, labels in train_dl:
            patches, labels = patches.to(device), labels.to(device)
            patches = patches.repeat(1, 3, 1, 1)
            patches = (patches - mean_gpu) / std_gpu
            optimiser.zero_grad()
            with torch.amp.autocast('cuda'):
                logits = patch_model(patches)
                loss = criterion(logits, labels)
            scaler.scale(loss).backward()
            scaler.step(optimiser)
            scaler.update()
            running_loss += loss.item() * len(labels)
        train_loss = running_loss / len(train_dl.dataset)

        patch_model.eval()
        val_loss, all_probs, all_labels = 0.0, [], []
        with torch.no_grad():
            for patches, labels in val_dl:
                patches, labels = patches.to(device), labels.to(device)
                patches = patches.repeat(1, 3, 1, 1)
                patches = (patches - mean_gpu) / std_gpu
                with torch.amp.autocast('cuda'):
                    logits = patch_model(patches)
                    loss_val = criterion(logits, labels)
                val_loss += loss_val.item() * len(labels)
                all_probs.extend(torch.sigmoid(logits).cpu().numpy())
                all_labels.extend(labels.cpu().numpy())
        val_loss /= len(val_dl.dataset)
        val_auc = roc_auc_score(all_labels, all_probs)
        scheduler.step(val_loss)

        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["val_auc"].append(val_auc)
        print(f"  Ep {epoch:02d}/{epochs}  train={train_loss:.4f}  val={val_loss:.4f}  auc={val_auc:.4f}")

        if val_loss < best_val_loss:
            best_val_loss, patience_ctr = val_loss, 0
            torch.save(patch_model.state_dict(), save_path)
            print(f"    ✓ Saved: {save_path.name}")
        else:
            patience_ctr += 1
            if patience_ctr >= patience:
                print(f"  Early stopping at epoch {epoch}")
                break

    del backbone, patch_model, optimiser
    gc.collect(); torch.cuda.empty_cache()
    return history, best_val_loss

"""### Attention-based Multiple Instance Learning (ABMIL) Architectures

Calculates attention weights for patches using
  gated attention mechanisms to aggregate patch features into a bag representation.
"""

class AttentionPool(nn.Module):
    def __init__(self, feat_dim, attn_dim, dropout=0.0, gated=False):
        super().__init__()
        self.gated = gated
        self.V = nn.Linear(feat_dim, attn_dim, bias=True)
        if gated:
            self.U = nn.Linear(feat_dim, attn_dim, bias=True)   # gate branch
        self.w = nn.Linear(attn_dim, 1, bias=False)
        self.dropout = nn.Dropout(dropout) if dropout > 0 else nn.Identity()

    def forward(self, h):
        if self.gated:
            feat = torch.tanh(self.V(h)) * torch.sigmoid(self.U(h))
        else:
            feat = torch.tanh(self.V(h))
        a = torch.softmax(self.w(self.dropout(feat)), dim=0)
        z = torch.sum(a * h, dim=0, keepdim=True)
        return z, a

"""Combines attention pooling with a final linear head to predict
  bag-level (whole-slide image) targets.
"""

class BagClassifier(nn.Module):
    def __init__(self, feat_dim, attn_dim, dropout=0.0, gated=False):
        super().__init__()
        self.attn = AttentionPool(feat_dim, attn_dim, dropout, gated=gated)
        self.head = nn.Linear(feat_dim, 1)

    def forward(self, h):
        z, a = self.attn(h)
        return self.head(z).squeeze(), a

"""### Cached Bag Data Processing

Groups extracted feature vectors by bag ID so whole-slide
  collections can be loaded efficiently during MIL training.
"""

class CachedBagDataset(Dataset):
    def __init__(self, features, y_np, bag_ids, bag_list):
        self.features, self.y, self.bag_ids, self.bag_list = features, y_np, bag_ids, bag_list

    def __len__(self):
        return len(self.bag_list)

    def __getitem__(self, idx):
        bid = self.bag_list[idx]
        mask = self.bag_ids == bid
        h = torch.from_numpy(self.features[mask]).float()
        bag_label = torch.tensor(self.y[mask][0], dtype=torch.float32)
        return h, bag_label

"""Custom collate function to handle variable numbers of patch
  embeddings per bag.
"""

def collate_cached(batch):
    return [item[0] for item in batch], torch.stack([item[1] for item in batch])

"""### Feature Extraction & Performance Metrics Evaluation

Pass raw patch images through a trained model backbone to
  extract and save low-dimensional feature embeddings.
"""

def extract_features(X_np, model, mean_gpu, std_gpu, device, batch_size=256):
    all_feats = []
    model.eval()
    with torch.no_grad():
        for start in range(0, len(X_np), batch_size):
            batch_np = X_np[start:start + batch_size]
            t = torch.from_numpy(batch_np).float().permute(0, 3, 1, 2).to(device)
            t = t.repeat(1, 3, 1, 1)
            t = (t - mean_gpu) / std_gpu
            with torch.amp.autocast('cuda'):
                feats = model(t).cpu().numpy()
            all_feats.append(feats)
    return np.concatenate(all_feats, axis=0)

"""Calculates evaluation metrics including ROC-AUC,
  F1-Score, Sensitivity, Specificity, MCC, Confusion Matrix and Calibration (ECE).
"""

def compute_all_metrics(y_true, y_probs, threshold, label=""):
    y_pred = (y_probs >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0.0
    fpr_val     = fp / (fp + tn) if (fp + tn) > 0 else 0.0
    mcc         = matthews_corrcoef(y_true, y_pred)

    prob_true, prob_pred = calibration_curve(y_true, y_probs, n_bins=10, strategy='uniform')
    bin_counts = np.histogram(y_probs, bins=np.linspace(0, 1, 11))[0]
    ece = float(np.sum(bin_counts[:len(prob_true)] * np.abs(prob_true - prob_pred)) / len(y_probs))

    metrics = {
        "threshold": threshold,
        "auc": float(roc_auc_score(y_true, y_probs)),
        "f1": float(f1_score(y_true, y_pred, zero_division=0)),
        "sensitivity": float(sensitivity),
        "specificity": float(specificity),
        "fpr": float(fpr_val),
        "mcc": float(mcc),
        "ece": ece,
        "tn": int(tn), "fp": int(fp), "fn": int(fn), "tp": int(tp),  # raw counts
    }
    if label:
        print(f"── {label} ──")
        for k, v in metrics.items():
            if k in ("tn", "fp", "fn", "tp"):
                continue
            print(f"  {k:15s}: {v:.4f}")
        print(f"  confusion      : TN={tn} FP={fp} FN={fn} TP={tp}")
    return metrics