# -*- coding: utf-8 -*-
"""config

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1crwa4eIFwIhW7-2f2JjGIAAsUI3QU0RB

# Central Configuration
This section establishes `config.py` as a single source of 'truth' across all project notebooks.
"""

import os
import numpy as np
import random

"""### Dataset and Output Directory Paths
Defines input file paths for the CBIS-DDSM dataset (label CSV files, PNG
images, and metadata) alongside the working directory path for Kaggle.
"""

LABELS_BASE = '/kaggle/input/datasets/mfjmrizvi/cbis-ddsm-tcia-labels'
PNG_ROOT = '/kaggle/input/datasets/mfjmrizvi/cbis-ddsm-png/CBIS-DDSM-PNG'
METADATA_CSV = f'{PNG_ROOT}/metadata.csv'

# CSV paths (official TCIA labels)
MASS_TRAIN_CSV = f'{LABELS_BASE}/mass_case_description_train_set.csv'
MASS_TEST_CSV  = f'{LABELS_BASE}/mass_case_description_test_set.csv'

# Output Paths
OUTPUT = '/kaggle/working'

"""### Model Parameters & Label Mapping
- Sets patch extraction hyper-parameters (dimensions, stride, sampling limit
  and variance thresholds).
- Configures global seed numbers to guarantee experiment reproducibility.
- Maps text pathology strings ('MALIGNANT', 'BENIGN') to binary target labels (1, 0).
"""

PATCH_SIZE  = 224
STRIDE      = 112
MIN_STD     = 15
MAX_PATCHES = 48
RANDOM_SEED = 42

LABEL_MAP = {
    'MALIGNANT':               1,
    'BENIGN':                  0,
    'BENIGN_WITHOUT_CALLBACK': 0
}

# Reproducibility
np.random.seed(RANDOM_SEED)
random.seed(RANDOM_SEED)

"""### Shared Pipeline Helper Functions

Parses file path strings to extract unique DICOM Series UIDs.
"""

def extract_series_uid(path_str, position=1):
    # Extract Series UID (second 1.3.6 segment) from CBIS-DDSM path.
    if __import__('pandas').isna(path_str):
        return None
    parts = str(path_str).replace('\\', '/').split('/')
    uids = [p for p in parts if p.startswith('1.3.6')]
    if len(uids) > position:
        return uids[position]
    elif len(uids) > 0:
        return uids[0]
    return None

"""Applies the label map to convert dataset pathology columns
  to numerical binary targets.
"""

def binarise_pathology(df):
    df = df.copy()
    df['label'] = df['pathology'].map(LABEL_MAP)
    return df

"""Constructs a lookup dictionary mapping Series UIDs
  to converted image PNG files ('full', 'mask', or 'crop')
"""

def build_path_map_from_metadata(metadata_df, series_desc, png_root, file_role):
    path_map = {}
    subset = metadata_df[metadata_df['Series Description'] == series_desc]
    for _, row in subset.iterrows():
        uid = str(row['Series UID'])
        candidate = f"{png_root}/{uid}/{file_role}.png"
        if os.path.exists(candidate):
            path_map[uid] = candidate
    return path_map

"""Merges mapped image file paths back into Pandas dataframes."""

def link_column_to_paths(df, column, path_map):
    # Add image path column to dataframe using path_map lookup.
    df = df.copy()
    paths = []
    for _, row in df.iterrows():
        uid = extract_series_uid(str(row[column]), position=1)
        paths.append(path_map.get(uid, None))
    return paths

print("Config loaded successfully")