# -*- coding: utf-8 -*-
"""abmil_common

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Ctah0bViHGZrmPy6Z0d0K_d5OWWGWnt
"""

"""
CM3015 Breast Cancer Detection: Shared ABMIL pipeline components
Used by NB03, NB04, NB05, NB07 (and any future backbone notebooks).
Identical logic to what was inline in NB03-05. This is a relocation,
not a rewrite. No prior results are affected by importing from here.
"""

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import gc
from torch.utils.data import Dataset
from sklearn.metrics import f1_score, roc_auc_score, confusion_matrix, roc_curve, matthews_corrcoef
from sklearn.calibration import calibration_curve
from torch.utils.data import DataLoader
import timm

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]


def get_normalisation_tensors(device):
    mean = torch.tensor(IMAGENET_MEAN, dtype=torch.float32, device=device).view(1, 3, 1, 1)
    std  = torch.tensor(IMAGENET_STD,  dtype=torch.float32, device=device).view(1, 3, 1, 1)
    return mean, std


def run_cv(feats_all, y_all, bag_ids_all, fold_ids, feat_dim,
           attn_dim=128, dropout=0.25, gated=True,
           lr=1e-4, weight_decay=1e-4, epochs=30, patience=7, n_folds=5,
           tag="", device=None):
    all_bags = np.unique(bag_ids_all)
    cv_results = []

    for fold in range(n_folds):
        train_bags = all_bags[fold_ids[all_bags] != fold]
        val_bags   = all_bags[fold_ids[all_bags] == fold]

        train_mask = np.isin(bag_ids_all, train_bags)
        val_mask   = np.isin(bag_ids_all, val_bags)

        train_ds = CachedBagDataset(feats_all[train_mask], y_all[train_mask],
                                     bag_ids_all[train_mask], train_bags)
        val_ds   = CachedBagDataset(feats_all[val_mask], y_all[val_mask],
                                     bag_ids_all[val_mask], val_bags)
        train_dl = DataLoader(train_ds, batch_size=1, shuffle=True, collate_fn=collate_cached)
        val_dl   = DataLoader(val_ds, batch_size=1, shuffle=False, collate_fn=collate_cached)

        # bag-level pos_weight for fold's train split
        train_bag_labels = np.array([y_all[bag_ids_all == b][0] for b in train_bags])
        n_pos = (train_bag_labels == 1).sum()
        n_neg = (train_bag_labels == 0).sum()
        pos_weight_val = n_neg / max(n_pos, 1)  # guard div-by-zero
        criterion = nn.BCEWithLogitsLoss(
            pos_weight=torch.tensor(pos_weight_val, device=device)
        )

        model = BagClassifier(feat_dim, attn_dim, dropout=dropout, gated=gated).to(device)
        optimiser = optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimiser, mode='min', factor=0.5, patience=3)

        best_val_loss, patience_ctr, best_state = float("inf"), 0, None
        for epoch in range(1, epochs + 1):
            model.train()
            for h_list, labels in train_dl:
                h, label = h_list[0].to(device), labels[0].to(device)
                optimiser.zero_grad()
                logit, _ = model(h)
                loss = criterion(logit, label)
                loss.backward()
                optimiser.step()

            model.eval()
            val_loss = 0.0
            with torch.no_grad():
                for h_list, labels in val_dl:
                    h, label = h_list[0].to(device), labels[0].to(device)
                    logit, _ = model(h)
                    val_loss += criterion(logit, label).item()
            val_loss /= len(val_ds)
            scheduler.step(val_loss)

            if val_loss < best_val_loss:
                best_val_loss, patience_ctr = val_loss, 0
                best_state = {k: v.clone() for k, v in model.state_dict().items()}
            else:
                patience_ctr += 1
                if patience_ctr >= patience:
                    break

        model.load_state_dict(best_state)
        model.eval()
        val_probs, val_true = [], []
        with torch.no_grad():
            for h_list, labels in val_dl:
                logit, _ = model(h_list[0].to(device))
                val_probs.append(torch.sigmoid(logit).item())
                val_true.append(labels[0].item())
        val_probs, val_true = np.array(val_probs), np.array(val_true)

        fpr_c, tpr_c, thresholds_c = roc_curve(val_true, val_probs)
        idx = np.argmax(tpr_c >= 0.90)
        thresh = float(thresholds_c[idx])
        m = compute_all_metrics(val_true, val_probs, thresh, f"[{tag}] Fold {fold}")
        m["fold"] = fold
        cv_results.append(m)

    cv_df = pd.DataFrame(cv_results)
    summary = cv_df[["auc","f1","sensitivity","specificity","fpr","mcc","ece"]].agg(["mean","std"])
    return cv_results, summary

def build_backbone(model_name, pretrained=True):
    return timm.create_model(model_name, pretrained=pretrained, num_classes=0)


class PatchDataset(Dataset):
    def __init__(self, X_np, y_np):
        self.X = X_np
        self.y = torch.from_numpy(y_np).float()

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        patch = torch.from_numpy(self.X[idx]).float()
        return patch.permute(2, 0, 1), self.y[idx]


class IndexedPatchDataset(Dataset):
    """Same as PatchDataset, but indexes into a shared array instead of
    copying a subset — avoids duplicating gigabytes of data per fold."""
    def __init__(self, X_all, y_all, indices):
        self.X = X_all
        self.y = torch.from_numpy(y_all[indices]).float()
        self.indices = indices

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, i):
        real_idx = self.indices[i]
        patch = torch.from_numpy(self.X[real_idx]).float()
        return patch.permute(2, 0, 1), self.y[i]


class PatchClassifier(nn.Module):
    def __init__(self, backbone, feat_dim):
        super().__init__()
        self.backbone = backbone
        self.head = nn.Linear(feat_dim, 1)

    def forward(self, x):
        return self.head(self.backbone(x)).squeeze(1)


def train_stage1_fold(model_name, X_all, y_all, train_idx, val_idx, class_weight_dict,
                       optimiser_name, lr, weight_decay, save_path,
                       device, patch_size=224, batch_size=128,
                       epochs=15, patience=5):
    # Trains ONE Stage 1 patch classifier and saves the best checkpoint.
    # Same procedure for every backbone and every fold so only model_name
    # and the parameters (optimiser/lr/weight_decay) differ between calls.

    backbone = build_backbone(model_name, pretrained=True).to(device)
    with torch.no_grad():
        _dummy = torch.zeros(2, 3, patch_size, patch_size, device=device)
        feat_dim = backbone(_dummy).shape[1]
    del _dummy

    patch_model = PatchClassifier(backbone, feat_dim).to(device)

    pos_weight_val = class_weight_dict[1] / class_weight_dict[0]
    criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight_val, device=device))

    if optimiser_name == "AdamW":
        optimiser = optim.AdamW(patch_model.parameters(), lr=lr, weight_decay=weight_decay)
    else:
        optimiser = optim.Adam(patch_model.parameters(), lr=lr, weight_decay=weight_decay)

    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimiser, mode='min', factor=0.5, patience=3)
    mean_gpu, std_gpu = get_normalisation_tensors(device)

    train_dl = DataLoader(IndexedPatchDataset(X_all, y_all, train_idx), batch_size=batch_size,
                           shuffle=True, num_workers=2, pin_memory=True)
    val_dl   = DataLoader(IndexedPatchDataset(X_all, y_all, val_idx), batch_size=batch_size,
                           shuffle=False, num_workers=2, pin_memory=True)

    scaler = torch.amp.GradScaler('cuda')
    best_val_loss, patience_ctr = float("inf"), 0
    history = {"train_loss": [], "val_loss": [], "val_auc": []}

    for epoch in range(1, epochs + 1):
        patch_model.train()
        running_loss = 0.0
        for patches, labels in train_dl:
            patches, labels = patches.to(device), labels.to(device)
            patches = patches.repeat(1, 3, 1, 1)
            patches = (patches - mean_gpu) / std_gpu
            optimiser.zero_grad()
            with torch.amp.autocast('cuda'):
                logits = patch_model(patches)
                loss = criterion(logits, labels)
            scaler.scale(loss).backward()
            scaler.step(optimiser)
            scaler.update()
            running_loss += loss.item() * len(labels)
        train_loss = running_loss / len(train_dl.dataset)

        patch_model.eval()
        val_loss, all_probs, all_labels = 0.0, [], []
        with torch.no_grad():
            for patches, labels in val_dl:
                patches, labels = patches.to(device), labels.to(device)
                patches = patches.repeat(1, 3, 1, 1)
                patches = (patches - mean_gpu) / std_gpu
                with torch.amp.autocast('cuda'):
                    logits = patch_model(patches)
                    loss_val = criterion(logits, labels)
                val_loss += loss_val.item() * len(labels)
                all_probs.extend(torch.sigmoid(logits).cpu().numpy())
                all_labels.extend(labels.cpu().numpy())
        val_loss /= len(val_dl.dataset)
        val_auc = roc_auc_score(all_labels, all_probs)
        scheduler.step(val_loss)

        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["val_auc"].append(val_auc)
        print(f"  Ep {epoch:02d}/{epochs}  train={train_loss:.4f}  val={val_loss:.4f}  auc={val_auc:.4f}")

        if val_loss < best_val_loss:
            best_val_loss, patience_ctr = val_loss, 0
            torch.save(patch_model.state_dict(), save_path)
            print(f"    ✓ Saved: {save_path.name}")
        else:
            patience_ctr += 1
            if patience_ctr >= patience:
                print(f"  Early stopping at epoch {epoch}")
                break

    del backbone, patch_model, optimiser
    gc.collect(); torch.cuda.empty_cache()
    return history, best_val_loss

class AttentionPool(nn.Module):
    def __init__(self, feat_dim, attn_dim, dropout=0.0, gated=False):
        super().__init__()
        self.gated = gated
        self.V = nn.Linear(feat_dim, attn_dim, bias=True)
        if gated:
            self.U = nn.Linear(feat_dim, attn_dim, bias=True)   # gate branch
        self.w = nn.Linear(attn_dim, 1, bias=False)
        self.dropout = nn.Dropout(dropout) if dropout > 0 else nn.Identity()

    def forward(self, h):
        if self.gated:
            feat = torch.tanh(self.V(h)) * torch.sigmoid(self.U(h))
        else:
            feat = torch.tanh(self.V(h))
        a = torch.softmax(self.w(self.dropout(feat)), dim=0)
        z = torch.sum(a * h, dim=0, keepdim=True)
        return z, a


class BagClassifier(nn.Module):
    def __init__(self, feat_dim, attn_dim, dropout=0.0, gated=False):
        super().__init__()
        self.attn = AttentionPool(feat_dim, attn_dim, dropout, gated=gated)
        self.head = nn.Linear(feat_dim, 1)

    def forward(self, h):
        z, a = self.attn(h)
        return self.head(z).squeeze(), a


class CachedBagDataset(Dataset):
    def __init__(self, features, y_np, bag_ids, bag_list):
        self.features, self.y, self.bag_ids, self.bag_list = features, y_np, bag_ids, bag_list

    def __len__(self):
        return len(self.bag_list)

    def __getitem__(self, idx):
        bid = self.bag_list[idx]
        mask = self.bag_ids == bid
        h = torch.from_numpy(self.features[mask]).float()
        bag_label = torch.tensor(self.y[mask][0], dtype=torch.float32)
        return h, bag_label


def collate_cached(batch):
    return [item[0] for item in batch], torch.stack([item[1] for item in batch])


def extract_features(X_np, model, mean_gpu, std_gpu, device, batch_size=256):
    all_feats = []
    model.eval()
    with torch.no_grad():
        for start in range(0, len(X_np), batch_size):
            batch_np = X_np[start:start + batch_size]
            t = torch.from_numpy(batch_np).float().permute(0, 3, 1, 2).to(device)
            t = t.repeat(1, 3, 1, 1)
            t = (t - mean_gpu) / std_gpu
            with torch.amp.autocast('cuda'):
                feats = model(t).cpu().numpy()
            all_feats.append(feats)
    return np.concatenate(all_feats, axis=0)


def compute_all_metrics(y_true, y_probs, threshold, label=""):
    y_pred = (y_probs >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0.0
    fpr_val     = fp / (fp + tn) if (fp + tn) > 0 else 0.0
    mcc         = matthews_corrcoef(y_true, y_pred)

    prob_true, prob_pred = calibration_curve(y_true, y_probs, n_bins=10, strategy='uniform')
    bin_counts = np.histogram(y_probs, bins=np.linspace(0, 1, 11))[0]
    ece = float(np.sum(bin_counts[:len(prob_true)] * np.abs(prob_true - prob_pred)) / len(y_probs))

    metrics = {
        "threshold": threshold,
        "auc": float(roc_auc_score(y_true, y_probs)),
        "f1": float(f1_score(y_true, y_pred, zero_division=0)),
        "sensitivity": float(sensitivity),
        "specificity": float(specificity),
        "fpr": float(fpr_val),
        "mcc": float(mcc),
        "ece": ece,
        "tn": int(tn), "fp": int(fp), "fn": int(fn), "tp": int(tp),  # raw counts
    }
    if label:
        print(f"── {label} ──")
        for k, v in metrics.items():
            if k in ("tn", "fp", "fn", "tp"):
                continue
            print(f"  {k:15s}: {v:.4f}")
        print(f"  confusion      : TN={tn} FP={fp} FN={fn} TP={tp}")
    return metrics