# -*- coding: utf-8 -*-
"""config

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1crwa4eIFwIhW7-2f2JjGIAAsUI3QU0RB
"""

# config.py
# Central configuration for CM3015 Breast Cancer Detection project
# Import this at the top of every notebook

import os
import numpy as np
import random

# === DATASET PATHS ===
AWSAF_BASE  = '/kaggle/input/datasets/awsaf49/cbis-ddsm-breast-cancer-image-dataset'
LABELS_BASE = '/kaggle/input/datasets/mfjmrizvi/cbis-ddsm-tcia-labels'
JPEG_ROOT   = f'{AWSAF_BASE}/jpeg'
PNG_ROOT = '/kaggle/input/datasets/mfjmrizvi/cbis-ddsm-png/CBIS-DDSM-PNG'
METADATA_CSV = f'{PNG_ROOT}/metadata.csv'

# CSV paths — official TCIA labels
MASS_TRAIN_CSV = f'{LABELS_BASE}/mass_case_description_train_set.csv'
MASS_TEST_CSV  = f'{LABELS_BASE}/mass_case_description_test_set.csv'
CALC_TRAIN_CSV = f'{LABELS_BASE}/calc_case_description_train_set.csv'
CALC_TEST_CSV  = f'{LABELS_BASE}/calc_case_description_test_set.csv'
DICOM_INFO_CSV = f'{AWSAF_BASE}/csv/dicom_info.csv'
META_CSV       = f'{AWSAF_BASE}/csv/meta.csv'

# === OUTPUT PATHS ===
OUTPUT = '/kaggle/working'

# === MODEL PARAMETERS ===
PATCH_SIZE  = 224
STRIDE      = 112
MIN_STD     = 15
MAX_PATCHES = 48
RANDOM_SEED = 42
BATCH_SIZE  = 32
EPOCHS      = 30
LR_INIT     = 1e-3
LR_FINETUNE = 1e-4
LR_FULL     = 1e-5

# === LABEL MAPPING ===
LABEL_MAP = {
    'MALIGNANT':               1,
    'BENIGN':                  0,
    'BENIGN_WITHOUT_CALLBACK': 0
}

# === REPRODUCIBILITY ===
np.random.seed(RANDOM_SEED)
random.seed(RANDOM_SEED)

# === HELPER FUNCTIONS USED ACROSS NOTEBOOKS ===
def extract_series_uid(path_str, position=1):
    """Extract Series UID (second 1.3.6 segment) from CBIS-DDSM path."""
    if __import__('pandas').isna(path_str):
        return None
    parts = str(path_str).replace('\\', '/').split('/')
    uids = [p for p in parts if p.startswith('1.3.6')]
    if len(uids) > position:
        return uids[position]
    elif len(uids) > 0:
        return uids[0]
    return None

def binarise_pathology(df):
    """Map pathology strings to binary labels."""
    df = df.copy()
    df['label'] = df['pathology'].map(LABEL_MAP)
    return df

def build_path_map(dicom_info_df, series_desc, jpeg_root):
    """Build SeriesUID -> jpeg path map for a given series type."""
    path_map = {}
    subset = dicom_info_df[
        dicom_info_df['SeriesDescription'] == series_desc
    ]
    for _, row in subset.iterrows():
        img_path = str(row['image_path'])
        uid = extract_series_uid(img_path, position=1)
        if uid:
            filename = img_path.replace('\\', '/').split('/')[-1]
            path_map[uid] = f"{jpeg_root}/{uid}/{filename}"
    return path_map

def build_path_map_from_metadata(metadata_df, series_desc, png_root, file_role):
    """
    Drop-in replacement for build_path_map, sourced from TCIA metadata.csv
    instead of the awsaf49 JPEG dataset's dicom_info.csv.
    file_role: 'full', 'mask', or 'crop' -- picks which converted PNG to
    point at, since mask+crop share one Series UID.
    """
    path_map = {}
    subset = metadata_df[metadata_df['Series Description'] == series_desc]
    for _, row in subset.iterrows():
        uid = str(row['Series UID'])
        candidate = f"{png_root}/{uid}/{file_role}.png"
        if os.path.exists(candidate):
            path_map[uid] = candidate
    return path_map

def link_column_to_paths(df, column, path_map):
    """Add image path column to dataframe using path_map lookup."""
    df = df.copy()
    paths = []
    for _, row in df.iterrows():
        uid = extract_series_uid(str(row[column]), position=1)
        paths.append(path_map.get(uid, None))
    return paths

print("Config loaded successfully")